config/routes.rb
Rails.application.routes.draw do
  root 'results#ranking_brasil'

  resources :results
  get 'power-ranking', controller: :results, action: :ranking_brasil
  resources :teams

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :team

  def self.period(start_date=nil, end_date=nil)
    start_date ||= Date.today-2.weeks
    end_date ||= Date.today
    joins(:team).where(date: start_date..end_date).group(:team_id)
        .select('sum(points) as total_points, team_id, state as team')
        .order('total_points desc, points desc')
        .map do |result|
      result.team = Team.find(result[:team_id])
      result
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :results

  validates_presence_of :name
  validates :name, uniqueness: true

  def period_results start_date, end_date
    start_date ||= Date.today-2.weeks
    end_date ||= Date.today
    results.where(date: start_date..end_date).order(date: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.order(date: :desc).all
  end

  def ranking_brasil
    @start_date = params[:start_date].blank? ? Date.today-2.weeks : Date.parse(params[:start_date])
    @end_date = params[:end_date].blank? ? Date.today : Date.parse(params[:end_date])
    @results = Result.period @start_date, @end_date
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to new_result_path, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:team_id, :description, :date, :state, :points)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
  def labeled_states results
    results.map do |result|
      color_class = 'red'
      if result.state == 'v'
        color_class = 'green'
      elsif result.state == 'e'
        color_class = 'orange'
      end
      content_tag :a, result.state, class: "ui #{color_class} label", title: result.description
    end.join('').html_safe
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PowerRanking</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="ui two column centered grid">
  <div class="column">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.collection_select :team_id, Team.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table border="1">
  <thead>
    <tr>
      <th>Team</th>
      <th>Description</th>
      <th>Date</th>
      <th>State</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.team.name %></td>
        <td><%= result.description %></td>
        <td><%= result.date %></td>
        <td><%= result.state %></td>
        <td><%= result.points %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/ranking_brasil.html.erb
<p id="notice"><%= notice %></p>

<div class="ui center aligned segment">
  <h1><%= semantic_icon('line chart') %> Power Ranking Brasil</h1>
  <div class="ui tertiary inverted segment">
    Ranking de resultados relativos dos times da Série A do Campeonato Brasileiro de Futebol 2015
  </div>
</div>

<%= form_tag power_ranking_path, method: :get do %>
    <div class="ui form">
      <div class="inline fields">
        <div class="field">
          De:
          <%= text_field_tag :start_date, (l(@start_date) unless @start_date.nil?) %>
        </div>
        <div class="field">
          até:
          <%= text_field_tag :end_date, (l(@end_date) unless @end_date.nil?) %>
        </div>
        <div class="field">
          <button type="submit" class="button ui icon"><%= semantic_icon('arrow right') %></button>
        </div>
      </div>
    </div>
<% end %>

<table class="ui table">
  <thead>
  <tr>
    <th>#</th>
    <th>Time</th>
    <th>Pontos</th>
    <th>Últimos Resultados</th>
  </tr>
  </thead>

  <tbody>
  <% @results.each_with_index do |result, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= result.team.name %></td>
        <td><%= result.total_points %></td>
        <td><%= labeled_states result.team.period_results @start_date, @end_date %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @result.team.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @result.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @result.date %>
</p>

<p>
  <strong>State:</strong>
  <%= @result.state %>
</p>

<p>
  <strong>Points:</strong>
  <%= @result.points %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>